spring.application.name=cisco-cybersecurity-platform
server.port=8080

# MongoDB Configuration
spring.data.mongodb.uri=mongodb://localhost:27017/cisco_cybersecurity_db
spring.data.mongodb.auto-index-creation=true

# Security / JWT Configuration
app.jwt.secret=9a36f6d8923a4a75a7c293774618e7e1b9338b1f58a8a4734a6e87f8976b92a4
app.jwt.expiration-ms=86400000

# CORS Configuration
app.cors.allowed-origins=http://localhost:5173,http://localhost:3000,http://127.0.0.1:5173

# Logging Configuration
logging.level.com.cisco.vip=INFO
logging.level.org.springframework.security=INFO
