import React, { useState, useEffect } from 'react';
import { useApp } from '../context/AppContext';
import { useAuth } from '../context/AuthContext';
import { Incident } from '../types';
import { api } from '../services/api';
import { CyberCard } from '../components/common/CyberCard';
import { Badge } from '../components/common/Badge';
import { Modal } from '../components/common/Modal';
import { 
  AlertOctagon, 
  ShieldAlert, 
  ShieldCheck, 
  AlertTriangle, 
  CheckCircle2, 
  XCircle, 
  FileText, 
  Terminal, 
  Filter,
  User,
  Clock,
  ArrowRight
} from 'lucide-react';

export const IncidentsView: React.FC = () => {
  const { incidents, refreshData, addToast } = useApp();
  const { user } = useAuth();
  const [selectedIncident, setSelectedIncident] = useState<Incident | null>(null);
  const [filterStatus, setFilterStatus] = useState<string>('ALL');
  const [containmentNotes, setContainmentNotes] = useState('');
  const [isUpdating, setIsUpdating] = useState(false);

  const handleUpdateStatus = async (newStatus: string, quarantineWorkload = false) => {
    if (!selectedIncident) return;
    try {
      setIsUpdating(true);
      const updated = await api.updateIncident(selectedIncident.id, {
        status: newStatus,
        containmentNotes: containmentNotes || `Status transitioned to ${newStatus} by ${user?.username || 'SecOps Admin'}.`,
        resolvedBy: user?.username || 'secadmin',
        quarantineWorkload
      });
      setSelectedIncident(updated);
      await refreshData();
      addToast(
        newStatus === 'RESOLVED' ? 'success' : 'info',
        `Incident #${updated.id} Updated`,
        `Incident status set to ${newStatus}.`
      );
    } catch (err: any) {
      addToast('danger', 'Update Failed', err.message || 'Could not update incident');
    } finally {
      setIsUpdating(false);
    }
  };

  const filteredIncidents = filterStatus === 'ALL'
    ? incidents
    : incidents.filter((i: Incident) => i.status === filterStatus);

  const getSeverityBadge = (sev: string) => {
    switch (sev) {
      case 'CRITICAL': return <Badge variant="danger" pulse>{sev}</Badge>;
      case 'HIGH': return <Badge variant="danger">{sev}</Badge>;
      case 'MEDIUM': return <Badge variant="warning">{sev}</Badge>;
      case 'LOW':
      default: return <Badge variant="neutral">{sev}</Badge>;
    }
  };

  const getStatusBadge = (st: string) => {
    switch (st) {
      case 'RESOLVED': return <Badge variant="success">RESOLVED</Badge>;
      case 'CONTAINED': return <Badge variant="purple">CONTAINED</Badge>;
      case 'INVESTIGATING': return <Badge variant="warning">INVESTIGATING</Badge>;
      case 'DETECTED':
      default: return <Badge variant="danger" pulse>DETECTED</Badge>;
    }
  };

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 p-5 rounded-2xl bg-slate-900/80 border border-slate-800">
        <div>
          <div className="flex items-center gap-2">
            <AlertOctagon className="w-5 h-5 text-rose-400" />
            <h1 className="text-lg sm:text-xl font-bold font-mono text-slate-100">
              Security Incident Response & Forensics Center
            </h1>
          </div>
          <p className="text-xs text-slate-400 mt-1">
            Real-Time Threat Triage • Packet Forensics Inspection • Automated Workload Quarantine & Containment
          </p>
        </div>

        <div className="flex items-center gap-2 text-xs font-mono">
          <span className="text-slate-400">Filter:</span>
          <select
            value={filterStatus}
            onChange={(e) => setFilterStatus(e.target.value)}
            className="bg-slate-950 border border-slate-700 rounded-lg px-3 py-1.5 text-cyan-300 outline-none"
          >
            <option value="ALL">All Statuses</option>
            <option value="DETECTED">Detected</option>
            <option value="INVESTIGATING">Investigating</option>
            <option value="CONTAINED">Contained</option>
            <option value="RESOLVED">Resolved</option>
          </select>
        </div>
      </div>

      {/* Incidents Table */}
      <CyberCard
        title={`Active Incident Queue (${filteredIncidents.length} Tickets)`}
        subtitle="Automated alerts generated by Stateful Firewall, SG, and K8s CNI policy enforcement"
        headerIcon={<ShieldAlert className="w-4 h-4 text-rose-400" />}
      >
        <div className="overflow-x-auto">
          <table className="w-full text-left text-xs font-mono">
            <thead>
              <tr className="border-b border-slate-800 text-slate-400">
                <th className="pb-3">INCIDENT ID</th>
                <th className="pb-3">SEVERITY</th>
                <th className="pb-3">TITLE & ATTACK VECTOR</th>
                <th className="pb-3">SOURCE → TARGET</th>
                <th className="pb-3">DETECTION SYSTEM</th>
                <th className="pb-3">STATUS</th>
                <th className="pb-3 text-right">ACTION</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-slate-800/60">
              {filteredIncidents.length === 0 ? (
                <tr>
                  <td colSpan={7} className="py-8 text-center text-slate-500">
                    No security incidents found in this category.
                  </td>
                </tr>
              ) : (
                filteredIncidents.map((inc: Incident) => (
                  <tr
                    key={inc.id}
                    onClick={() => setSelectedIncident(inc)}
                    className="hover:bg-slate-800/30 transition-colors cursor-pointer"
                  >
                    <td className="py-3 font-bold text-cyan-400">#{inc.id}</td>
                    <td className="py-3">{getSeverityBadge(inc.severity)}</td>
                    <td className="py-3">
                      <span className="font-bold text-slate-100">{inc.title}</span>
                      <p className="text-[11px] text-slate-400 mt-0.5">{inc.attackType}</p>
                    </td>
                    <td className="py-3 text-slate-300">
                      <span className="text-rose-400">{inc.sourceWorkload || inc.sourceIp}</span> → <span className="text-cyan-400">{inc.targetWorkload || inc.targetIp}</span>
                    </td>
                    <td className="py-3 text-[11px] text-slate-400">{inc.detectionMechanism}</td>
                    <td className="py-3">{getStatusBadge(inc.status)}</td>
                    <td className="py-3 text-right">
                      <button
                        onClick={(e) => {
                          e.stopPropagation();
                          setSelectedIncident(inc);
                        }}
                        className="px-2.5 py-1 rounded bg-slate-800 hover:bg-slate-700 text-cyan-300 border border-slate-700"
                      >
                        Inspect
                      </button>
                    </td>
                  </tr>
                ))
              )}
            </tbody>
          </table>
        </div>
      </CyberCard>

      {/* Incident Detail & Forensics Modal */}
      {selectedIncident && (
        <Modal
          isOpen={!!selectedIncident}
          onClose={() => setSelectedIncident(null)}
          title={`Incident Forensics Ticket #${selectedIncident.id}`}
          subtitle={selectedIncident.title}
          maxWidth="2xl"
        >
          <div className="space-y-4 font-mono text-xs">
            {/* Meta Row */}
            <div className="grid grid-cols-2 sm:grid-cols-4 gap-3 p-3 rounded-xl bg-slate-950 border border-slate-800">
              <div>
                <span className="text-[10px] text-slate-400 uppercase">Severity</span>
                <div className="mt-1">{getSeverityBadge(selectedIncident.severity)}</div>
              </div>
              <div>
                <span className="text-[10px] text-slate-400 uppercase">Current Status</span>
                <div className="mt-1">{getStatusBadge(selectedIncident.status)}</div>
              </div>
              <div>
                <span className="text-[10px] text-slate-400 uppercase">Triggered At</span>
                <p className="text-slate-200 mt-1">{new Date(selectedIncident.timestamp).toLocaleTimeString()}</p>
              </div>
              <div>
                <span className="text-[10px] text-slate-400 uppercase">Action Taken</span>
                <p className="text-emerald-400 font-bold mt-1">{selectedIncident.actionTaken}</p>
              </div>
            </div>

            {/* Attack Flow & Rule */}
            <div className="p-3.5 rounded-xl bg-slate-950 border border-slate-800 space-y-2">
              <div className="flex items-center justify-between">
                <span className="text-slate-400">ATTACK VECTOR:</span>
                <span className="text-rose-400 font-bold">{selectedIncident.attackType}</span>
              </div>
              <div className="flex items-center justify-between">
                <span className="text-slate-400">SOURCE → DESTINATION:</span>
                <span className="text-slate-200">{selectedIncident.sourceWorkload || selectedIncident.sourceIp} → {selectedIncident.targetWorkload || selectedIncident.targetIp}</span>
              </div>
              <div className="flex items-center justify-between">
                <span className="text-slate-400">TRIGGERED POLICY RULE:</span>
                <span className="text-cyan-300 font-bold">{selectedIncident.ruleTriggered}</span>
              </div>
            </div>

            {/* Forensics Payload Dump */}
            <div>
              <span className="text-slate-400 block mb-1.5 font-bold">PACKET FORENSICS PAYLOAD (JSON):</span>
              <pre className="p-3 rounded-xl bg-slate-950 border border-slate-800 text-[11px] text-cyan-300 overflow-x-auto">
                {JSON.stringify(selectedIncident.forensicPayload, null, 2)}
              </pre>
            </div>

            {/* Containment Notes */}
            <div>
              <label className="block text-slate-400 mb-1">SOC Investigator Containment Notes</label>
              <textarea
                rows={2}
                value={containmentNotes}
                onChange={(e) => setContainmentNotes(e.target.value)}
                placeholder="Add mitigation actions taken, sandbox quarantine status, or patch notes..."
                className="w-full bg-slate-950 border border-slate-700 rounded-lg p-2.5 text-slate-100 focus:border-cyan-400 outline-none"
              />
            </div>

            {/* Action Triage Buttons */}
            <div className="pt-3 border-t border-slate-800 flex flex-wrap items-center justify-between gap-2">
              <div className="flex items-center gap-2">
                <button
                  type="button"
                  disabled={isUpdating}
                  onClick={() => handleUpdateStatus('INVESTIGATING')}
                  className="px-3 py-1.5 rounded-lg bg-amber-950 text-amber-300 border border-amber-800 hover:bg-amber-900"
                >
                  Mark Investigating
                </button>
                <button
                  type="button"
                  disabled={isUpdating}
                  onClick={() => handleUpdateStatus('CONTAINED', true)}
                  className="px-3 py-1.5 rounded-lg bg-purple-950 text-purple-300 border border-purple-800 hover:bg-purple-900"
                >
                  Quarantine & Contain
                </button>
              </div>

              <div className="flex items-center gap-2">
                <button
                  type="button"
                  disabled={isUpdating}
                  onClick={() => handleUpdateStatus('RESOLVED')}
                  className="px-4 py-1.5 rounded-lg bg-emerald-600 hover:bg-emerald-500 text-white font-bold shadow-cyber-emerald"
                >
                  Mark Resolved
                </button>
              </div>
            </div>
          </div>
        </Modal>
      )}
    </div>
  );
};
